export const tradingConfig = {
  initialCapital: 100,
  positionSizePercent: 25,
  maxRiskPerTradePercent: 2,
  maxDailyLossPercent: 5,
  maxWeeklyLossPercent: 10,
  maxDrawdownBeforeStopPercent: 15,
  minimumProfitFactorForPaperTrading: 1.3,
  minimumTradesForValidation: 20,
  minimumWinRateForValidation: 40,
  minimumExpectancyForValidation: 0,
  minimumWinRateForPaperTrading: 40,
  monteCarloMinimumTrades: 10,
  monteCarloPreferredTrades: 30,
  walkForwardTrainingWindow: 60,
  walkForwardTestingWindow: 20,
} as const;
